site_name: Freenit
site_url: https://freenit-framework.github.io/
repo_url: https://github.com/freenit-framework/freenit-framework.github.io
repo_name: freenit-framework/freenit-framework.github.io
theme:
  name: material
  logo: img/logo.png
  favicon: img/logo.png
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
plugins:
  - search
  - awesome-pages
